Alias: $loinc = http://loinc.org
Alias: $DocCode = http://esveikata.lt/classifier/DocCode

ValueSet: LtEspbiVsDocumentTypeCodes
Id: lt-espbi-vs-doc-typecodes
Description: "Dokumentų tipų kodų sąrašas / Document type codes. Naudojamas LtEspbiComposition.type (CodeableConcept)."
* ^version = "1.0.0"
* ^status = #draft
* ^date = "2026-01-08"
* $loinc#34108-1 "Ambulatorinio apsilankymo aprašymas"
* $loinc#47420-5 "Ambulatorinių slaugos paslaugų namuose poreikio vertinimo klausimynas"
* $loinc#18594-2 "Asmens psichikos sveikatos istorija"
* $loinc#68683-2 "Atlikti tikrinimai"
* $loinc#11488-4 "Atsakymas į siuntimą"
* $loinc#57833-6 "Elektroninis receptas"
* $loinc#57074-7 "Gimdymo eiga"
* $loinc#67796-3 "Greitosios medicinos pagalbos kvietimo kortelė"
* $loinc#57130-7 "Gydytojo dienynas"
* $loinc#11502-2 "Laboratorinio tyrimo rezultatų (duomenų) protokolas"
* $loinc#X-LAB-ORDER "Laboratorinio tyrimo užsakymas"
* $loinc#18748-4 "Medicininio vaizdo aprašymas"
* $loinc#57133-1 "Medicinos dokumentų išrašas / siuntimas"
* $loinc#57717-1 "Naujagimio pirma apžiūra"
* $loinc#92015-7 "Naujagimis (-iai)"
* $loinc#67471-3 "Nėštumo duomenys, anamnezė"
* $loinc#57083-8 "Nėštumo ir gimdymo istorija"
* $loinc#69045-3 "Nėštumo nutrūkimo / nutraukimo patvirtinimo aktas"
* $loinc#90767-5 "Nėštumo suvestinė"
* $loinc#57059-8 "Nėščiosios ambulatorinio apsilankymo aprašymas"
* $loinc#57077-0 "Nėščiosios ir naujagimio kortelė"
* $loinc#92574-3 "Nėščiosios tyrimas, gimdymo priežiūros planas, paskyrimai"
* $loinc#64295-9 "Paciento slaugos ir priežiūros planas"
* $loinc#60591-5 "Paciento suvestinės dokumentas"
* $loinc#34129-7 "Paciento sveikatos būklės vertinimo lapas"
* $loinc#96134-2 "Paciento veiklos ir namų aplinkos vertinimo lapas"
* $loinc#11526-1 "Patologijos tyrimo atsakymas"
* $loinc#X-PATH-ORDER "Patologijos tyrimo užsakymas"
* $loinc#34782-3 "Pranešimas apie nustatytą (įtariamą) infekcinį susirgimą ar būklę"
* $loinc#78706-9 "Pranešimas apie pirmą kartą nustatytą onkologinės ligos diagnozę"
* $loinc#75423-4 "Psichikos ir elgesio sutrikimų, vartojant narkotines ir psichotropines medžiagas, statistinės apskaitos duomenų aprašas"
* $loinc#92016-5 "Rizikos veiksniai"
* $loinc#18842-5 "Stacionaro epikrizė"
* $loinc#73814-6 "Tyrimai ir procedūros nėštumo metu"
* $loinc#60593-1 "Vaisto išdavimas"
* $loinc#11369-6 "Vakcinacijos įrašas"
* SNOMED_CT#224406003 "Asmens medicininė knygelė (sveikatos pasas) (Darbdavio dalis)"
* SNOMED_CT#171363009 "Asmens medicininė knygelė (sveikatos pasas) (Gydytojo dalis)"
* SNOMED_CT#184822001 "Asmens privalomojo sveikatos tikrinimo kortelė"
* SNOMED_CT#307930005 "Medicininis mirties liudijimas"
* SNOMED_CT#270101008 "Medicininis perinatalinis mirties liudijimas"
* SNOMED_CT#160922003 "Privalomojo sveikatos patikrinimo medicininė pažyma (Darbdavio dalis)"
* SNOMED_CT#275674000 "Privalomojo sveikatos patikrinimo medicininė pažyma (Gydytojo dalis)"
* SNOMED_CT#444561001 "Vaiko gimimo pažymėjimas"
* SNOMED_CT#274410002 "Vaiko sveikatos pažymėjimas (Odontologo dalis)"
* SNOMED_CT#171387006 "Vaiko sveikatos pažymėjimas (Šeimos gydytojo dalis)"
* SNOMED_CT#270370004 "Vairuotojo sveikatos patikrinimo medicininė pažyma"
* SNOMED_CT#241491007 "Vaisiaus ultragarsinis tyrimas"
* $DocCode#01.0002 "Cezario pjūvio operacijos protokolas"
* $DocCode#01.0007 "Naujagimio raidos istorija"
* $DocCode#01.0006 "Negyvagimio / naujagimio mirties atvejo priežasčių nagrinėjimas"
* $DocCode#01.0004 "Nėštumo, gimdymo ar pogimdyminio laikotarpio arti netekties ir netekties atvejai"
* $DocCode#01.0001 "Pagalbos teikimo kontrolinis lapas"
* $DocCode#01.0003 "Partograma"
* $DocCode#01.0005 "Tėvų sutikimas dėl naujagimiui atliekamų procedūrų"