Alias: $special-user-type = https://ws.esveikata.lt/cxf/Classifiers/special-user-type
Alias: $role-type = https://ws.esveikata.lt/cxf/Classifiers/role-type

ValueSet: LtEspbiVsRoleTypeCodes
Id: lt-espbi-vs-role-type-codes
Description: "Vaidmenų tipų sąrašas / Role type codes. Naudojamas LtEspbiPractitionerRole.code (CodeableConcept)."
* ^version = "1.0.0"
* ^status = #draft
* ^date = "2026-01-12"
* $special-user-type#scientist "Akademikas, mokslininkas"
* $special-user-type#espbi_administrator "ESPBI IS administratorius"
* $special-user-type#ESPBI_consultant "ESPBI Konsultantas"
* $special-user-type#ESPBI_business "ESPBI eSveikatos skyrius"
* $special-user-type#espbi_system "ESPBI sistema"
* $special-user-type#his_system "HIS sistema"
* $special-user-type#ipr_system_gpuser "IPR sisteminis naudotojas - kaip bendrinis specialistas"
* $special-user-type#coordinator "Koordinuojančios institucijos specialistas"
* $special-user-type#temp_user "Laikinas naudotojas"
* $special-user-type#medvais_system "MEDVAIS sistema"
* $special-user-type#auditor "Medicinos auditorius"
* $special-user-type#ndnt_administrator "NDNT administratorius"
* $special-user-type#ndnt_user "NDNT naudotojas"
* $special-user-type#bus_administrator "PV administratorius"
* $special-user-type#sodra_administrator "SODRA administratorius"
* $special-user-type#sodra_user "SODRA naudotojas-atjungiama"
* $special-user-type#his_administrator "SPĮ administratorius"
* $special-user-type#vapris_system "VAPRIS sistema"
* $special-user-type#vlk_administrator "VLK administratorius"
* $special-user-type#vlk_user "VLK naudotojas"
* $special-user-type#pharmacy_administrator "Vaistinės administratorius"
* $special-user-type#pharmacy_system "Vaistinės sistema"
* $role-type#105 "Alternatyviosios medicinos specialistas"
* $role-type#7 "Farmacinės veiklos vadovas"
* $role-type#9 "Farmakotechnikas"
* $role-type#3 "Greitosios medicinos pagalbos specialistas"
* $role-type#25 "Išplėstinės praktikos vaistininkas"
* $role-type#204 "Kitas medicininis personalas"
* $role-type#5 "Klinikinio kodavimo specialistas"
* $role-type#264 "Licencijuotas sveikatos specialistas"
* $role-type#86 "Odontologijos kitas personalas"
* $role-type#104 "Onkologijos ligų prevencijos ir atvejo vadybos specialistai"
* $role-type#148 "Optikos darbuotojas"
* $role-type#10 "PV darbuotojas"
* $role-type#144 "Psichikos sveikatos slaugytojas"
* $role-type#145 "Psichikos sveikatos specialistas"
* $role-type#4 "Registratūros darbuotojas"
* $role-type#44 "SODRA naudotojas"
* $role-type#146 "Skubiosios medicinos gydytojas"
* $role-type#2 "Slaugos ir akušerijos specialistas"
* $role-type#147 "Slaugos koordinatorius"
* $role-type#1 "Sveikatos priežiūros specialistas"
* $role-type#84 "TPNC specialistas"
* $role-type#45 "VASPVT naudotojas"
* $role-type#24 "VLK,TLK darbuotojas"
* $role-type#124 "VRM Medicinos centro ekspertas"
* $role-type#6 "Vaistininkas"
* $role-type#8 "Vaistinės atstovas PASPĮ"
* $role-type#87 "Visuomenės sveikatos specialistas"
* $role-type#64 "Šeimos gydytojo komandos narys"