Alias: $loinc = http://loinc.org
Alias: $DocSectionCode = http://esveikata.lt/classifiers/DocSectionCode
Alias: $DocCode = http://esveikata.lt/classifier/DocCode

ValueSet: LtEspbiVsDocumentSectionCodes
Id: lt-espbi-vs-doc-section-codes
Description: "Dokumentų sekcijų kodų sąrašas / Document section codes. Naudojamas LtEspbiComposition.section.code (CodeableConcept)."
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = false
* ^date = "2026-01-09"
* $loinc#55107-7 " Prisegtos bylos / Attached files"
* $loinc#64295-9 "ASPN Paciento slaugos ir priežiūros planas"
* $loinc#48765-2 "Alergijos / Allergies"
* $loinc#11348-0 "Anamnezė / Anamnesis"
* $loinc#11526-1 "Ankstesni morfologiniai tyrimai (data, tyrimo vieta ir registracijos Nr.) /  Earlier morphological tests (date, test location and registration no.)"
* $loinc#69043-8 "Anksčiau gimusių vaikų (gyvų ir negyvagimių) skaičius / Previous born babies number "
* $loinc#52799-4 "Ar buvo atlikta operacija (-os) per paskutines 28 dienas iki mirties? / Any operations before death have been performed?"
* $loinc#77974-4 "Asmuo hospitalizuotas / Whether the patient was hospitalized for condition of interest"
* $loinc#47519-4 "Atliktos chirurginės procedūros / Performed surgery procedures"
* $loinc#30954-2 "Atliktų laboratorinių ir instrumentinių tyrimų aprašymas / Performed lab tests description"
* $loinc#34075-2 "Atliktų laboratorinių ir instrumentinių tyrimų informacija / Info about diagnostic/lab results"
* $loinc#57079-6 "Birth plan narrative"
* $loinc#11640-0 "Births total"
* $loinc#3137-7 "Body height Measured"
* $loinc#3141-9 "Body weight Measured"
* $loinc#8716-3 "Būklės įvertinimas (objektyviai) / Objective condition"
* $loinc#11961-0 "Cervix [Length] US"
* $loinc#8690-0 "Chirurginės procedūros (per pastaruosius 6 mėn.) / History of surgical procedures Narrative"
* $loinc#10167-5 "Chirurginės procedūros prieš pastaruosius šešis mėnesius / History of surgical procedures Narrative"
* $loinc#57719-7 "Conditions tested for in this newborn screening study"
* $loinc#11527-9 "Diagnozių aprašymas / Description of Diagnosis"
* $loinc#11535-2 "Diagnozių sąrašas / Diagnosis"
* $loinc#101573-4 "Diet at discharge"
* $loinc#58199-1 "Dokumento pateikimo/keitimo/šalinimo paaiškinimas / Document submission/update/delete description"
* $loinc#60593-1 "Dokumento tipas / Document type"
* $loinc#57833-6 "Dokumento tipas / Document type"
* $loinc#21958-4 "Dozė / Dose"
* $loinc#21964-2 "Dozės matavimo vienetas / Dose measurement unit"
* $loinc#95376-0 "Duomenys apie gyvūną, kuris sužalojo žmogų / Type of animal exposed to"
* $loinc#10157-6 "Family history"
* $loinc#12116-0 "Fetal Umbilical cord Study observation US"
* $loinc#84429-0 "GMP kortelės ne FHIR struktūros duomenys prisegti kaip bylos / Level 3 emergency medical services patient care report - recommended CDA R1 and R2 set"
* $loinc#72115-9 "Gaivinimas / Resuscitation attempted"
* $loinc#8290-9 "Galvos apimtis / Head Occipital-frontal circumference --at birth"
* $loinc#73789-0 "General physical condition [NSRAS]"
* $loinc#18185-9 "Gestacinis amžius / Gestational age"
* $loinc#11888-5 "Gestational age US composite estimate"
* $loinc#15508-5 "Gimdymas / Labor and delivery records"
* $loinc#48767-8 "Gydymo, slaugos, darbo, ambulatorines priežiūros rekomendacijos duomenys / Treatment recommendations data"
* $loinc#11510-5 "Gydymo, slaugos, darbo, ambulatorinės priežiūros rekomendacijos (aprašymas) / Treatment recommendations"
* $loinc#39223-3 "Gydymo, slaugos, darbo, ambulatorinės priežiūros rekomendacijos (aprašymas) / Treatment recommendations"
* $loinc#39221-7 "Gydymo, slaugos, darbo, ambulatorinės priežiūros rekomendacijos / Recommendations for treatment"
* $loinc#69449-7 "Gydytojo nuomone mirties rūšis / Death type (by Practitioner conclusion)"
* $loinc#72056-5 "HB vakcinacija / Hepatitis B vaccination received"
* $loinc#67471-3 "History of Pregnancy"
* $loinc#57080-4 "Implantai / Implants"
* $loinc#67163-6 "Informacija apie atliktus diagnostinius tyrimus ligai nustatyti ir jų rezultatus / Diagnostic procedures performed [PhenX]"
* $loinc#60484-3 "Informacija apie atliktą skiepą / Information about performed vaccination"
* $loinc#11488-4 "Informacija apie atliktų laboratorinių ir instrumentinių tyrimų rezultatų medicininius dokumentus (dokumento pavadinimas, data) / Info about diagnostic/lab results documents"
* $loinc#57139-8 "Informacija apie išrašytus siuntimo dokumentus (E027, E200, E014) / Info about prepared order (E027, E200, E014) documents"
* $loinc#59779-9 "Informacija apie pakartotinai numatomus skiepus / Information about next vaccinations (if any)"
* $loinc#57133-1 "Informacija apie siunčiamą medicininį dokumentą (medicininio dokumento pavadinimas, data) / Info about medical docs sent to police"
* $loinc#34108-1 "Informacija apie susietą E025 (jeigu gydymas tęsiamas) / Info about previous E025 if treatment is continued"
* $loinc#55110-1 "Išvada / Conclusion"
* $loinc#73569-6 "Jonizuojančios spinduliuotės duomenys / Radiation information"
* $loinc#73771-8 "Kelintas gimdymas / Which birth in a row it is"
* $loinc#68991-9 "Kita epidemiologiškai svarbi informacija / Epidemiologically important information for public health reporting panel"
* $loinc#68346-6 "Kitos svarbios patologinės būklės, sąlygojusios mirtį, bet nesusijusios su pagrindine mirties priežastimi / Other conditions (not related to main death reason)"
* $loinc#69441-4 "Kitų aplinkybių paaiškinimas /  Other explanation of the death circumstances"
* $loinc#72231-4 "Konsultuojančio gydytojo atsakymas / Consult reply note"
* $loinc#56796-6 "Kontaktiniai asmenys ypatingu atveju / Emergency contact information panel"
* $loinc#76426-6 "Kreipimosi (atvykimo į SPĮ) data / Start date for episode of care"
* $loinc#57074-7 "Labor and delivery process"
* $loinc#92574-3 "Labor and delivery summary - recommended IHE set"
* $loinc#10158-4 "Ligos (gyvenimo) anamnezė / Disease (life) Anamnesis"
* $loinc#67188-3 "Ligos forma / Type of complication - infection"
* $loinc#46098-0 "Lytis / Sex"
* $loinc#92016-5 "Maternal pregnancy risk factors Document"
* $loinc#11518-8 "Medicininiai duomenys / Clinical Data"
* $loinc#55752-0 "Medicininiai duomenys / Clinical Data"
* $loinc#69437-2 "Medicininį mirties liudijimą išrašė /  Death Certificate author type"
* $loinc#10160-0 "Medikamentų vartojimo istorija / History of medication use Narrative"
* $loinc#21984-0 "Mirties priežastys / Death circumstances"
* $loinc#69442-2 "Moteris mirė / Timing of recent pregnancy in relation to death "
* $loinc#74025-8 "Motina / Mother identifier"
* $loinc#57712-2 "Motinos išsilavinimas / Mothers education"
* $loinc#12132-7 "Narrative [Interpretation] Study observation general"
* $loinc#73772-6 "Naujagimis (negyvagimis) gimė / Which dead born in a row it is (First, first of twins, second of twins, more than two babies)"
* $loinc#77753-2 "Naviko morfologija / Tumor morphology panel Cancer"
* $loinc#11374-6 "Nelaimingo atsitikimo, savižudybės, žmogžudystės aplinkybės / Incident(cause to death) circumstances"
* $loinc#31211-6 "Nelaimingo atsitikimo, savižudybės, žmogžudystės data / Incident date (cause to death)"
* $loinc#58332-8 "Nelaimingo atsitikimo, savižudybės, žmogžudystės vieta / Place of accident, suicide or homicide"
* $loinc#62387-6 "Nemedikamentinis / Performed non-medical Treatment description"
* $loinc#92015-7 "Newborn administrative information"
* $loinc#57717-1 "Newborn screen card data panel"
* $loinc#57130-7 "Newborn screening report - overall interpretation"
* $loinc#18594-2 "Nuoroda į Psichikos sveikatos duomenų priedą E030 / Reference to Mental Health Data Annex"
* $loinc#34792-2 "Nusiskundimai / Complaints"
* $loinc#75322-8 "Nusiskundimų aprašas / Complaint info"
* $loinc#49052-4 "Nėštumo diena / Gestational age in days"
* $loinc#42228-7 "Nėštumo informacija / Pregnancy information"
* $loinc#11885-1 "Nėštumo savaitė pagal mėnesines / Gestational age Estimated from last menstrual period"
* $loinc#49051-6 "Nėštumo trukmė (sav.) / Gestational age in weeks"
* $loinc#73814-6 "Obstetric procedures performed"
* $loinc#28183-2 "Oral mucous membranes impairment [CCC]"
* $loinc#52463-7 "Paciento identifikavimo žyma / Patient identifiaction mark"
* $loinc#34129-7 "Paciento sveikatos būklės vertinimo forma"
* $loinc#96134-2 "Paciento veiklos ir namų aplinkos vertinimo forma"
* $loinc#18782-3 "Pagrindinė diagnozė / Main diagnosis"
* $loinc#52535-2 "Papildomi duomenys / Additional Data"
* $loinc#46513-8 "Papildomos diagnozės / Additional diagnoses"
* $loinc#LP30630-5 "Pelvis\\u003eUterine artery"
* $loinc#11349-8 "Persirgtų ligų istorija / History of Past illness"
* $loinc#8694-2 "Physical findings of Abdomen"
* $loinc#11422-3 "Physical findings of Chest"
* $loinc#8701-5 "Physical findings of Head"
* $loinc#8702-3 "Physical findings of Heart"
* $loinc#32455-8 "Physical findings of Muscle tone"
* $loinc#8705-6 "Physical findings of Nervous system"
* $loinc#32460-8 "Physical findings of Palate"
* $loinc#11443-9 "Physical findings of Respiratory system"
* $loinc#8710-6 "Physical findings of Thorax and Lungs"
* $loinc#57075-4 "Pirmoji naujagimio apžiūra namuose / Information in Case of Newborn Baby Examination (at home)"
* $loinc#93037-0 "Portable medical order form"
* $loinc#100483-7 "Požymis \\"
* $loinc#101439-8 "Požymis \\"
* $loinc#100591-7 "Požymis \\"
* $loinc#44944-7 "Pranešimai policijos elektroninių paslaugų sistemai / The list of alerts to police"
* $loinc#57059-8 "Pregnancy visit summary note"
* $loinc#60569-1 "Prisegtų bylų skaičius / Number of attached files"
* $loinc#18738-5 "Psichiatrinė anamnezė ir (ar) psichikos sveikatos būsena / Psychiatric anamnesis and/or mental health status"
* $loinc#83906-8 "Psichikos rizikos veiksniai / Mental risk factors"
* $loinc#75423-4 "Psichotropinių priklausomybių klausimynas (ASIS)"
* $loinc#55283-6 "Pulso dažnio būklė / Fetal Heart rate"
* $loinc#46467-7 "Rizikos veiksniai / Risk factors "
* $loinc#82593-5 "Skiepijimų istorija / Immunization summary report"
* $loinc#11369-6 "Skiepų skyrimai / Immunization orders"
* $loinc#46046-9 "Skin condition section"
* $loinc#57828-6 "Skiriami vaistai ir MPP / Prescribed medications"
* $loinc#65842-7 "Skyrimo(-ų)(Order) būsenos pakeitimas / Order(s) status changing OrderResponse(s)"
* $loinc#39016-1 "Spėjamas amžius (m., mėn., d.), kai mirusiojo tapatybė nenustatyta / hypothetical age (years, months, days)"
* $loinc#55114-3 "Susiję tyrimai / Related tests"
* $loinc#85585-8 "Susirgimo (ligos simptomų pradžia) / Date of condition onset"
* $loinc#29463-7 "Svoris / Body weight"
* $loinc#55753-8 "Taikytas gydymas / Performed treatment"
* $loinc#89812-2 "Taikytas medikamentinis gydymas / Performed medication treatment"
* $loinc#10183-2 "Taikytas medikamentinis gydymas / Performed medication treatment"
* $loinc#89497-2 "Tyrimai / Mother\\u0027s Prenatal tests"
* $loinc#18834-2 "Tyrimo (medicininio vaizdo) aprašas / Test (medical view) description"
* $loinc#11513-9 "Tyrimo (medicininio vaizdo) aprašymo numeris / Test (medical view) description ID"
* $loinc#19005-8 "Tyrimo ACHI kodas / Test ACHI code"
* $loinc#55113-5 "Tyrimo UID / Test UID"
* $loinc#55111-9 "Tyrimo aprašymo informacija / Diagnostic report information"
* $loinc#18779-9 "Tyrimo data ir laikas / Test date and time"
* $loinc#18771-6 "Tyrimo pavadinimas / Test name"
* $loinc#56851-9 "Tyrimų / konsultacijų planas (paskirti tyrimų ir konsultacijų siuntimai, diagnozių sąrašas) / Tests and Consultations Plan"
* $loinc#18776-5 "Tyrimų / konsultacijų planas / Tests and Consultations Plan"
* $loinc#80770-1 "Tyrimų / konsultacijų plano aprašymas / Tests and Consultations Plan description"
* $loinc#56447-6 "Tyrimų / konsultacijų plano aprašymas / Tests and Consultations Plan description"
* $loinc#34970-4 "Ultragarsinio tyrimo data / Ultrasound date"
* $loinc#LP7696-0 "Uterine artery.left"
* $loinc#LP7697-8 "Uterine artery.right"
* $loinc#55281-0 "Vaisių skaičius / Number of fetuses"
* $loinc#57852-6 "Ypatingų indikatorių sąrašas / Alerts list"
* $loinc#11996-6 "[#] Pregnancies"
* $loinc#34104-0 "pecialistų konsultacijos / Specialists consultations"
* $loinc#20564-1 "ĮKŠY SpO2(%) / Oxygen saturation in Blood"
* $loinc#74711-3 "Įrenginio serijinis numeris / Device serial number"
* $loinc#8302-2 "Ūgis / Body height"
* $loinc#8306-3 "Ūgis / Height"
* SNOMED_CT#17542004 "Accident while engaged in work-related activity (event)"
* SNOMED_CT#43408002 "Akių dugno raudono reflekso tyrimas (+/–) / Red reflex"
* SNOMED_CT#394704008 "Ankstesnės profesijos ir stažas, metais / Previous jobs and years of work"
* SNOMED_CT#37823000 "Antros grupės kategorijos / Group II driving category"
* SNOMED_CT#364154000 "Appearance of anus (observable entity)"
* SNOMED_CT#365349005 "Apribojimai / Limitations"
* SNOMED_CT#443942000 "Asmuo, kuris kreipėsi dėl pažymos išrašymo / Person requested this certificate"
* SNOMED_CT#42284007 "BCG vakcinacija / BCG vaccination"
* SNOMED_CT#302787001 "Bilirubin measurement (procedure)"
* SNOMED_CT#405176005 "Blood glucose status (observable entity)"
* SNOMED_CT#396550006 "Blood test (procedure)"
* SNOMED_CT#124923004 "C-reactive protein reaction, function (observable entity)"
* SNOMED_CT#708130001 "Coombs test"
* SNOMED_CT#159553004 "Darbdavio dokumentą pildančio naudotojo duomenys / Employment clerk"
* SNOMED_CT#224373009 "Darbo stažas pagal šią profesiją, metais / Years of work at that position"
* SNOMED_CT#394571004 "Darbovietė / Workplace"
* SNOMED_CT#247583006 "Decision making"
* SNOMED_CT#111989001 "Defecation, function (observable entity)"
* SNOMED_CT#171351004 "Dokumento duomenys / Document Data"
* SNOMED_CT#406194006 "Dokumento duomenys / Document data"
* SNOMED_CT#169811007 "Dokumento duomenys / Document data"
* SNOMED_CT#58322009 "Dokumento galiojimo pabaiga / Document expired at date"
* SNOMED_CT#224361009 "Dokumentą pildančio naudotojo pareigos / Author job position title"
* SNOMED_CT#224406003 "Dokumentą pildančio naudotojo pareigos / Author job position title"
* SNOMED_CT#27624003 "ESI neregistruotos dabartinės, lėtinės ligos"
* SNOMED_CT#289707002 "Finding of regularity of uterine contraction"
* SNOMED_CT#300474003 "Finding of urine output (finding)"
* SNOMED_CT#307929000 "Galutinis / laikinas dokumentas / Final or Temporary  certificate"
* SNOMED_CT#364204002 "Genital observable (observable entity)"
* SNOMED_CT#184099003 "Gimdymo data ir laikas / Birth delivery date and time"
* SNOMED_CT#169812000 "Gimdymo vieta / Birth delivery place"
* SNOMED_CT#299231009 "Hip joint observation"
* SNOMED_CT#55923008 "Infant diet"
* SNOMED_CT#387760006 "Infusion care"
* SNOMED_CT#365389004 "Išduotas nedarbingumo pažymėjimas / pažyma / Certificate given (Incapacity for Work, Maternity leave, some Medical certificate)"
* SNOMED_CT#440337002 "Išduotas nedarbingumo pažymėjimas / pažyma / Certificate of Incapacity for Work"
* SNOMED_CT#243883003 "Išvada / Conclusion"
* SNOMED_CT#301707001 "Išvados duomenys / Conclusion data"
* SNOMED_CT#307930005 "Keičiamas liudijimas / Replaced temporary certificate"
* SNOMED_CT#160909006 "Kenksmingi veiksniai darbe / Harmful factors at work"
* SNOMED_CT#35018000 "Kitos kategorijos / Other driving category"
* SNOMED_CT#252623004 "Klausos tikrinimas OAE / Oto-acoustic emission test"
* SNOMED_CT#160922003 "Klinikiniai duomenys / Clinical Data"
* SNOMED_CT#365636006 "Kraujo grupė / Blood group"
* SNOMED_CT#103695000 "Medicininės pažymos / Medical certificate data"
* SNOMED_CT#399753006 "Mirties data / Date of death"
* SNOMED_CT#184305005 "Mirties priežastys: pagrindinės ligos (traumos), sukėlusios mirtį, kodas / Death cause (main disease code)"
* SNOMED_CT#366044004 "Mirties vieta / Death place"
* SNOMED_CT#419620001 "Mirtis / Death"
* SNOMED_CT#184096005 "Mirusiojo naujagimio pavardė / Baby surname"
* SNOMED_CT#371484003 "Mirusiojo naujagimio vardas / Baby name"
* SNOMED_CT#47340003 "Naujagimio kūno masė / Baby weight"
* SNOMED_CT#263495000 "Naujagimio lytis / Baby gender"
* SNOMED_CT#302080006 "Naujagimio, mirusio nuo 7 iki 28 parų, išnešiojimas / Pregnancy completion"
* SNOMED_CT#371508000 "Naviko stadija / Tumor stage"
* SNOMED_CT#237364002 "Negyvagimis / mirė pirmą gyvenimo savaitę / Baby death type (Born dead or died during the first week)"
* SNOMED_CT#386369002 "Newborn monitoring"
* SNOMED_CT#184225006 "Nuoroda į naujagimio paciento resursą (jeigu mire po gimimo) / Link to baby patient if died after born"
* SNOMED_CT#446059004 "Nustatytas nedarbingumas / Work ability index score"
* SNOMED_CT#21134002 "Nustatytas neįgalumas / Disability defined"
* SNOMED_CT#229056002 "Nustatyti specialūs poreikiai / Special needs register"
* SNOMED_CT#310506006 "Nėštumo nutraukimo priežastis / Reason for termination of pregnancy"
* SNOMED_CT#57485005 "Oxygen therapy care"
* SNOMED_CT#112115002 "Oxytocin"
* SNOMED_CT#444301002 "Paciento (motinos) duomenys / Babies mothers patient data"
* SNOMED_CT#133933007 "Paciento (naujagimio) duomenys / New born Patient data"
* SNOMED_CT#257445002 "Paciento fotografija /Picture"
* SNOMED_CT#108257001 "Patologinis mirusio negyvagimio/naujagimio tyrimas / Anatomic pathology procedure"
* SNOMED_CT#173300003 "Perinatalinės mirties priežastys: pagrindinės motinos ligos ar būklės (placentos būklės), lėmusios naujagimio mirtį, kodas / Death cause (Mother main disease)"
* SNOMED_CT#35683002 "Phototherapy of newborn"
* SNOMED_CT#55121009 "Pirmos grupės kategorijos / Group I driving category"
* SNOMED_CT#184104002 "Profesijos kodas / Occupation (job) code"
* SNOMED_CT#133877004 "Regimen orders"
* SNOMED_CT#80943009 "Risk factor"
* SNOMED_CT#32709003 "Socialinė paciento istorija / Social patient history"
* SNOMED_CT#364700005 "Specialios rekomendacijos / Special recommendations"
* SNOMED_CT#444135009 "Spėjamas amžius (dienomis), kai mirusiojo tapatybė nenustatyta / baby hypothetical age (in days)"
* SNOMED_CT#182816009 "Therapeutic prescription"
* SNOMED_CT#241491007 "Ultrasound scan of fetus"
* SNOMED_CT#266955002 "Įdarbinimo ar darbo sąlygų keitimo data / Employment date"
* $DocSectionCode#02.0903 "Akušerinių replių panaudojimas"
* $DocSectionCode#02.2334 "Ankstesni nėštumai ir jų baigtys"
* $DocSectionCode#02.1021 "Apgar balas po 1 min"
* $DocSectionCode#02.1027 "Apgar balas po 10 min"
* $DocSectionCode#02.1024 "Apgar balas po 5 min"
* $DocSectionCode#01.0106 "Apsirengt bei apsiauti pagalbos poreikio vertinimas"
* $DocSectionCode#01.0134 "Artimųjų asmenų dalyvivimo slaugoje vertinimas"
* $DocSectionCode#01.0104 "Asmens higienos ir rengimosi pagalbos poreikio vertinimas"
* $DocSectionCode#02.0931 "Atlikti veiksmai"
* $DocSectionCode#02.2005 "Baigtis"
* $DocSectionCode#02.0933 "Bendra informacija pagalbos teikimo pabaigoje"
* $DocSectionCode#01.0119 "Bendravimo vertinimas"
* $DocSectionCode#02.1202 "Bendroji Cesario Pjuvio Operacijos informacija"
* $DocSectionCode#02.0507 "Bendroji informacija apie nėštumo nutraukimo aprašą"
* $DocSectionCode#02.2102 "Bevandenis laikotarpis"
* $DocSectionCode#02.1402 "Būklė hospitalizuojant"
* $DocSectionCode#02.1208 "Cesario Pjuvio Operacijos eiga"
* $DocSectionCode#01.0002 "Cezario pjūvio operacijos protokolas"
* $DocSectionCode#02.0351 "Didelės rizikos nėštumo veiksniai"
* $DocSectionCode#02.2333 "ESI neregistruotos alergijos"
* $DocSectionCode#02.1327 "Epiziotomija"
* $DocSectionCode#02.2305 "Folinės r. vartojimas"
* $DocSectionCode#02.03561 "GVT (PE) Rizikos veiksniai"
* $DocSectionCode#02.0356 "GVT (PE) rizikos vertinimas ir prevencija nėštumo metu"
* $DocSectionCode#02.0357 "GVT (PE) rizikos vertinimas ir prevencija po gimdymo"
* $DocSectionCode#02.03582 "GVT (PE) rizikos vertinimas ir prevencija po gimdymo rizikos indikatorius"
* $DocSectionCode#02.03572 "GVT rizikos veiksniai"
* $DocSectionCode#02.1018 "Gaivinimas"
* $DocSectionCode#02.1020 "Gaivinimo trukmė (min)"
* $DocSectionCode#01.0135 "Galutinis ASPN poreikio vertinimas"
* $DocSectionCode#01.0138 "Galutinis ASPN poreikio vertinimas balais"
* $DocSectionCode#02.0405 "Gimdos priedų išvaizda"
* $DocSectionCode#02.03571 "Gimdymo būdas"
* $DocSectionCode#02.1303 "Gimdymo pradžios būdas"
* $DocSectionCode#02.1302 "Gimdymo pradžios būdas"
* $DocSectionCode#02.0354 "Gimdymo rizika"
* $DocSectionCode#02.03579 "Gimdymo rizikos indikatorius"
* $DocSectionCode#02.03541 "Gimdymo rizikos veiksniai"
* $DocSectionCode#02.1330 "Gimdymo skausmo malšinimas medikamentinis"
* $DocSectionCode#02.1331 "Gimdymo skausmo malšinimas nemedikamentinis"
* $DocSectionCode#02.1328 "Gimdymo takai"
* $DocSectionCode#02.2312 "Gimdymo terminas"
* $DocSectionCode#02.2314 "Gimdymo terminas pagal paskutines mėnesines"
* $DocSectionCode#02.2315 "Gimdymo terminas pagal ultragarsinį tyrimą"
* $DocSectionCode#02.2101 "Gimdymo trukmė"
* $DocSectionCode#02.1003 "Gimdymo vieta"
* $DocSectionCode#01.0112 "Griuvimo rizikos vertinimas"
* $DocSectionCode#01.0125 "Gyvenamosios vietos aplinkos pritaikymo vertinimas"
* $DocSectionCode#01.0105 "Higienos pagalbos poreikio vertinimas"
* $DocSectionCode#02.2335 "Informacija iš Paciento ESI"
* $DocSectionCode#02.1326 "Intervencijos"
* $DocSectionCode#01.0113 "Judesių koordinacijos sutrikimo vertinimas"
* $DocSectionCode#01.0109 "Judėjimo ir transportavimo pagalbos poreikio vertinimas"
* $DocSectionCode#01.0111 "Judėjimo vertinimas"
* $DocSectionCode#01.0121 "Kalbos sutrikimo vertinimas"
* $DocSectionCode#01.0132 "Kineziterapeuto paslaugos poreikio vertinimas"
* $DocSectionCode#02.2202 "Kita motinos liga  lėmusi naujagimio mirtį"
* $DocSectionCode#02.1153 "Kita svarbi informacija"
* $DocSectionCode#02.2205 "Kitos būklės"
* $DocSectionCode#01.0108 "Klausos sutrikimo vertinimas"
* $DocSectionCode#00.020513 "Klinikinis: M"
* $DocSectionCode#00.020512 "Klinikinis: N"
* $DocSectionCode#00.020511 "Klinikinis: T"
* $DocSectionCode#01.0110 "Kūno padėties vertinimas"
* $DocSectionCode#02.1001 "Medicininiai duomenys"
* $DocSectionCode#02.1601 "Medicininiai duomenys"
* $DocSectionCode#02.1501 "Medicininiai duomenys"
* $DocSectionCode#02.1301 "Medicininiai duomenys"
* $DocSectionCode#02.0615 "Medicininiai duomenys"
* $DocSectionCode#02.1201 "Medicininiai duomenys"
* $DocSectionCode#01.0136 "Minčių raiškos sutrikimo vertinimas"
* $DocSectionCode#02.0611 "Moteris mirė"
* $DocSectionCode#02.0914 "Moters būklė"
* $DocSectionCode#02.2318 "Moters žalingi įpročiai (iki nėštumo)"
* $DocSectionCode#02.2323 "Moters žalingi įpročiai (nėštumo metu)"
* $DocSectionCode#02.2308 "Mėnesinių ciklas"
* $DocSectionCode#02.2310 "Mėnesinių ciklo trukmė"
* $DocSectionCode#02.2309 "Mėnesinių trukmė"
* $DocSectionCode#02.2307 "Mėnesinės"
* $DocSectionCode#02.0100 "NGN antraštė"
* $DocSectionCode#02.1401 "NGN stacionaro medicininiai duomenys"
* $DocSectionCode#02.1004 "Naujagimio įrašas"
* $DocSectionCode#00.02042 "Naviko diferencialinio laipsnio kodas"
* $DocSectionCode#00.02041 "Naviko diferencialinis laipsnis"
* $DocSectionCode#00.02032 "Naviko morfologijos kodas"
* $DocSectionCode#02.2203 "Negyvagimio/Naujagimio mirties aplinkybės"
* $DocSectionCode#02.03511 "Nepalanki akušerinė anamnezė"
* $DocSectionCode#02.03513 "Nepalanki nėščiosios būklė"
* $DocSectionCode#02.1325 "Netekto kraujo kiekis"
* $DocSectionCode#02.0134 "Nėštumo diena"
* $DocSectionCode#02.04151 "Nėštumo diena pagal ankstyvą ultragarsinį tyrimą"
* $DocSectionCode#02.04150 "Nėštumo diena pagal mėnesines"
* $DocSectionCode#02.2301 "Nėštumo duomenys"
* $DocSectionCode#02.0131 "Nėštumo kortelės unikalus ID"
* $DocSectionCode#02.03512 "Nėštumo patologija"
* $DocSectionCode#02.0132 "Nėštumo pirmoji diena"
* $DocSectionCode#02.0133 "Nėštumo savaitė"
* $DocSectionCode#02.0610 "Nėštumo, gimdymo ar pogimdyminiu laikotarpio arti netekties ir netekties atvejai"
* $DocSectionCode#02.1404 "Nėščiosios būklės vertinimas"
* $DocSectionCode#02.03515 "Nėščiosios ligos"
* $DocSectionCode#02.1415 "Nėščiosios tyrimas per makštį"
* $DocSectionCode#02.2306 "Nėščiąją prižiūri"
* $DocSectionCode#00.0207 "Onkologinės ligos diagnozės nustatymo aplinkybės"
* $DocSectionCode#00.0208 "Onkologinės ligos diagnozės patvirtinimo būdas (nurodyti vieną ar daugiau)"
* $DocSectionCode#01.0117 "Orientacijos erdvėje sutrikimo vertinimas"
* $DocSectionCode#01.0116 "Orientacijos laike sutrikimo vertinimas"
* $DocSectionCode#01.0115 "Orientacijos sutrikimo vertinimas"
* $DocSectionCode#02.0410 "PI"
* $DocSectionCode#02.0407 "PI"
* $DocSectionCode#02.2338 "Pacientės pateikta informacija"
* $DocSectionCode#02.1307 "Pagalbos būdas"
* $DocSectionCode#02.0912 "Pagalbos teikimas pogimdyminio kraujavimo atveju"
* $DocSectionCode#02.0939 "Pagalbos teikimo pabaiga"
* $DocSectionCode#02.1305 "Pagimdė"
* $DocSectionCode#02.0613 "Pagrindinė mirties priežastis"
* $DocSectionCode#02.0419 "Papildomas tyrimas"
* $DocSectionCode#02.1607 "Papildomi priežiūros plano įrašai"
* $DocSectionCode#02.1504 "Partogramos įrašai"
* $DocSectionCode#02.2311 "Paskutinių normalių mėnesinių data"
* $DocSectionCode#00.05801 "Paskutinį kartą buvimo darbe ar vaikų ugdymo įstaigoje"
* $DocSectionCode#00.02010 "Pastabos Vėžio Registrui"
* $DocSectionCode#02.0913 "Pastebėtas pogimdyminis kraujavimas"
* $DocSectionCode#01.0122 "Pateiktos informacijos suvokimo vertinimas"
* $DocSectionCode#00.020523 "Patologinis: M"
* $DocSectionCode#00.020522 "Patologinis: N"
* $DocSectionCode#00.020521 "Patologinis: T"
* $DocSectionCode#02.0518 "Patvirtinimo data"
* $DocSectionCode#02.2313 "Patvirtintas gimdymo terminas"
* $DocSectionCode#02.1705 "Paveldimos medžiagų apykaitos ligos"
* $DocSectionCode#02.2328 "Persirgtos ir gretutinės ligos"
* $DocSectionCode#02.2302 "Pirmo apsilankymo data"
* $DocSectionCode#02.1314 "Placentos atributai"
* $DocSectionCode#02.1329 "Placentos užgimimo laikas"
* $DocSectionCode#02.1427 "Planuojami tyrimai"
* $DocSectionCode#02.1321 "Plyšimai"
* $DocSectionCode#02.0355 "Pogimdyminio kraujavimo rizika"
* $DocSectionCode#02.03580 "Pogimdyminio kraujavimo rizikos indikatorius"
* $DocSectionCode#02.03551 "Pogimdyminio kraujavimo rizikos veiksniai"
* $DocSectionCode#02.2316 "Preliminari nėštumo ir gimdymo atostogų pradžios data"
* $DocSectionCode#02.0353 "Priešlaikinio gimdymo rizika"
* $DocSectionCode#02.03578 "Priešlaikinio gimdymo rizikos indikatorius"
* $DocSectionCode#02.03531 "Priešlaikinio gimdymo rizikos veiksniai"
* $DocSectionCode#02.0412 "Protodiastolinė banga"
* $DocSectionCode#02.0409 "Protodiastolinė banga"
* $DocSectionCode#02.0508 "Psichologo konsultacija"
* $DocSectionCode#01.0114 "Pusiausvyros sutrikimo vertinimas"
* $DocSectionCode#02.0411 "RI"
* $DocSectionCode#02.0408 "RI"
* $DocSectionCode#01.0107 "Regėjimo sutrikimo vertinimas"
* $DocSectionCode#02.0418 "Rekomendacijos"
* $DocSectionCode#02.0902 "Replių ir vakuuminio ekstraktoriaus naudojimas"
* $DocSectionCode#02.03581 "Rizikos lygmuo"
* $DocSectionCode#02.1308 "Robsono grupė"
* $DocSectionCode#01.0120 "Samonės sutrikimo vertinimas"
* $DocSectionCode#01.0102 "Savirūpos pagalbos poreikio vertinimas"
* $DocSectionCode#01.0101 "Savirūpos vertinimas"
* $DocSectionCode#01.0118 "Savęs suvokimo vertinimas"
* $DocSectionCode#02.0421 "Skirta konsultacija pas"
* $DocSectionCode#02.1310 "Skirti antibiotikai"
* $DocSectionCode#01.0131 "Slaugytojo padėjėjo paslaugos reguliarumo vertinimas"
* $DocSectionCode#01.0130 "Slaugytojo padėjėjo poreikio vertinimas"
* $DocSectionCode#01.0128 "Slaugytojo paslaugos poreikio vertinimas"
* $DocSectionCode#01.0129 "Slaugytojo paslaugų reguliarumo vertinimas"
* $DocSectionCode#02.0510 "Socialinio darbuotojo konsultacija"
* $DocSectionCode#01.0137 "Socialinės paslaugos poreikio vertinimas"
* $DocSectionCode#01.0127 "Specialistų pagalbos poreikio vertinimas"
* $DocSectionCode#01.0126 "Specializuotos priežiūros poreikio vertinimas"
* $DocSectionCode#01.0123 "Sprendimų priėmimo sugebėjimo vertinimas"
* $DocSectionCode#02.0516 "Taikytas gimdymas"
* $DocSectionCode#02.0403 "Tyrimo sąlygos"
* $DocSectionCode#02.0401 "Tyrimo tikslai"
* $DocSectionCode#02.1801 "Tėvų sutikimas dėl naujagimiui atliekamų procedūrų"
* $DocSectionCode#02.2330 "Vaiko biologinio tėvo amžius"
* $DocSectionCode#02.1409 "Vaisiaus būklės vertinimas"
* $DocSectionCode#02.1502 "Vaisiaus duomenys"
* $DocSectionCode#02.03514 "Vaisiaus patologija"
* $DocSectionCode#02.0950 "Vaisiaus pečių užstrigimas"
* $DocSectionCode#02.1605 "Vaisiaus tyrimo informacija"
* $DocSectionCode#02.0426 "Vaisiaus tyrimo informacija."
* $DocSectionCode#01.0124 "Vaistų vartojimo vertinimas"
* $DocSectionCode#02.0905 "Vakuuminės ekstrakcijos panaudojimas"
* $DocSectionCode#01.0103 "Valgymo ir gėrimo pagalbos poreikio vertinimas"
* $DocSectionCode#02.1011 "Virkštelės kraujo pH/Lac"
* $DocCode#01.0004 "Nėštumo, gimdymo ar pogimdyminiu laikotarpio arti netekties ir netekties atvejai"
* $DocCode#01.0001 "Pagalbos teikimo kontrolinis lapas"
* $DocCode#01.0003 "Partograma"
* $DocCode#01.0005 "Tėvų sutikimas dėl naujagimiui atliekamų procedūrų"