CodeSystem: LtLabTestGroups
Id: lt-lab-test-groups
Title: "LT LAB tyrimų grupės"
* ^meta.versionId = "1"
* ^meta.lastUpdated = "2024-08-07T16:50:01.173+00:00"
* ^language = #lt
* ^version = "0.3.28"
* ^status = #active
* ^experimental = false
* ^date = "2024-04-25T00:00:00Z"
* ^publisher = "Registrų Centras"
* ^contact.name = "Registrų Centras"
* ^contact.telecom[0].system = #url
* ^contact.telecom[=].value = "https://www.registrucentras.lt/"
* ^contact.telecom[+].system = #email
* ^contact.telecom[=].value = "esveikata@registrucentras.lt"
* ^jurisdiction = urn:iso:std:iso:3166#LT "Lithuania"
* ^caseSensitive = true
* ^hierarchyMeaning = #is-a
* ^content = #complete
* ^property.code = #display
* ^property.uri = "http://terminology.hl7.org/CodeSystem/designation-usage|display"
* ^property.description = "Display"
* ^property.type = #string
* #BC "Bendrosios citologijos tyrimai"
* #BC #FERT "Nevaisingumo tyrimai"
* #BC #UA "Šlapimo tyrimai"
* #BM "Bendrosios mikrobiologijos tyrimai"
* #BM #BMT "Mikrobiologiniai tyrimai"
* #BM #PAR "Parazitologiniai tyrimail"
* #BM #TB "Tuberkuliozės tyrimai"
* #BT "Biocheminiai tyrimai"
* #BT #BT-ALC "Alkoholiai"
* #BT #BT-CANCER "Vėžio"
* #BT #BT-CARB "Angliavandeniai"
* #BT #BT-CARDIO "Širdies"
* #BT #BT-DRUG "Narkotinės medžiagos"
* #BT #BT-EL "Elektrolitai"
* #BT #BT-ENDO "Endokrininiai"
* #BT #BT-ENZ "Fermentai"
* #BT #BT-FE "Geležies"
* #BT #BT-GAS "Rūgščių-šarmų pusiausvyros"
* #BT #BT-HEP "Kepenų"
* #BT #BT-IL "Citokinai"
* #BT #BT-LIP "Lipidų"
* #BT #BT-MED "Vaistai"
* #BT #BT-MICRO "Mikroelementai"
* #BT #BT-MIN "Mineralų"
* #BT #BT-OTH "Kiti biocheminiai"
* #BT #BT-PEF "Baltymų elektroforezė"
* #BT #BT-PROT "Baltymai"
* #BT #BT-REN "Inkstų"
* #BT #BT-VIT "Vitaminai"
* #COAG "Kraujo krešėjimo tyrimai"
* #COAG #IM-COAG "Krešėjimo serologiniai tyrimai"
* #HEM "Laboratorinės hematologijos tyrimai"
* #HEM #KRBAN "Kraujo bankas (transfuziologijos) tyrimai"
* #IM "Imunologiniai tyrimai"
* #IM #ALERG "Alergologijos tyrimai"
* #IM #AUTO-SERO "Autoantikūnai"
* #IM #AUTOIM "Autoimuniteto tyrimai"
* #IM #CELLMARK "Ląstelių biožymenys"
* #IM #IM-CELL "Ląstelinio imuniteto tyrimai"
* #IM #IM-HUM "Humoralinio imuniteto tyrimai"
* #IM #IM-INNATE "Nespecifinio/įgimto imuniteto tyrimai"
* #IM #TOLER "Imuninės tolerancijos tyrimai"
* #IM #TRANSP "HLA/HNA/HPA"
* #INF-SER "Infekcinės serologijos tyrimai"
* #INF-SER #INF-MOL "Molekuliniai infekcijų tyrimai"
* #MOLGEN "Molekuliniai tyrimai"
* #MOLGEN #MOL-CITO "Citogenetiniai tyrimai"
* #MOLGEN #MOL-DNR "DNR diagnostikos tyrimai"
* #MOLGEN #MOL-KARY "Kariotipavimo tyrimai"
* #MOLGEN #MOL-ONCO "Onkogenetiniai tyrimai"
* #MOLGEN #MOL-PROT "Baltymų raiškos tyrimai"
* #MOLGEN #MOL-RNR "RNR raiškos tyrimai"